name: Node.js CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        os:
          - macOS-latest
          - ubuntu-latest
        node-version: [14.x, 16.x, 17.x]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm ci
      - run: npm run types:check
      - run: npm run format:check
      - run: npm run lint
      - run: npm run lint:css
      - run: npm test
      - run: npm run build
        env:
          CI: true
